name: RemoteChest
main: se.xtralarge.remotechest.RemoteChest
version: 1.1beta
author: getninjaN
depend: [Vault,WorldGuard]
commands:
  remotechest:
    description: Allows you to set and open a remote chest.
    usage: /remotechest [set/open] [x]
    aliases: [chest,rc,remc,remotec,rchest,remchest]